main:
  - name: 홈
    url: ""
    weight: 10

  - name: 이력서
    url: resume
    weight: 100

  - name: 자격증
    url: certificate
    weight: 200

  - name: 프로젝트
    url: project
    weight: 300

  - name: 연락처
    url: contact
    weight: 700
