main:
  - name: home
    url: ""
    weight: 10

  - name: resume
    url: resume
    weight: 100

  - name: certificate
    url: certificate
    weight: 200

  - name: project
    url: project
    weight: 300

  - name: contact
    url: contact
    weight: 700
